// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MantisBTTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:LoginPage:AdministratorLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    assertThat(driver.findElement(By.xpath("//span[contains(.,\'administrator\')]")).getText(), is("administrator"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addUserTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageUserPage:AddUser");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Manage")).click();
    driver.findElement(By.linkText("Manage Users")).click();
    driver.findElement(By.cssSelector(".form-title .button-small")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.xpath("//input[@name=\'username\']")).sendKeys("username001");
    driver.findElement(By.name("realname")).click();
    driver.findElement(By.xpath("//input[@name=\'realname\']")).sendKeys("username001");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.xpath("//input[@name=\'email\']")).sendKeys("username@username.it");
    driver.findElement(By.name("access_level")).click();
    {
      WebElement dropdown = driver.findElement(By.name("access_level"));
      dropdown.findElement(By.xpath("//option[. = 'updater']")).click();
    }
    driver.findElement(By.xpath("//option[@value=\'40\']")).click();
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Manage Users")).click();
    {
      String value = driver.findElement(By.name("username")).getAttribute("value");
      assertThat(value, is("username001"));
    }
    {
      String value = driver.findElement(By.xpath("//input[@name=\'realname\']")).getAttribute("value");
      assertThat(value, is("username001"));
    }
    {
      String value = driver.findElement(By.xpath("//input[@name=\'email\']")).getAttribute("value");
      assertThat(value, is("username@username.it"));
    }
    {
      WebElement element = driver.findElement(By.xpath("//select[@name=\'access_level\']"));
      String value = element.getAttribute("value");
      String locator = String.format("option[@value='%s']", value);
      String selectedText = element.findElement(By.xpath(locator)).getText();
      assertThat(selectedText, is("updater"));
    }
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addExistingUserFailsTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageUserPage:AddExistingUserFails");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Manage")).click();
    driver.findElement(By.linkText("Manage Users")).click();
    driver.findElement(By.xpath("//input[@value=\'Create New Account\']")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.xpath("//input[@name=\'username\']")).sendKeys("username001");
    driver.findElement(By.name("realname")).click();
    driver.findElement(By.xpath("//input[@name=\'realname\']")).sendKeys("username001");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.xpath("//input[@name=\'email\']")).sendKeys("username@username.it");
    driver.findElement(By.name("access_level")).click();
    {
      WebElement dropdown = driver.findElement(By.name("access_level"));
      dropdown.findElement(By.xpath("//option[. = 'updater']")).click();
    }
    driver.findElement(By.xpath("//option[@value=\'40\']")).click();
    driver.findElement(By.xpath("//input[@value=\'Create User\']")).click();
    assertThat(driver.findElement(By.xpath("//p[contains(.,\'That username is already being used. Please go back and select another one.\')]")).getText(), is("That username is already being used. Please go back and select another one."));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addEmptyUserFailsTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageUserPage:AddEmptyUserFails");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Manage")).click();
    driver.findElement(By.linkText("Manage Users")).click();
    driver.findElement(By.xpath("//input[@value=\'Create New Account\']")).click();
    driver.findElement(By.xpath("//input[@value=\'Create User\']")).click();
    assertThat(driver.findElement(By.xpath("//p[contains(.,\'A necessary field \"\" was empty. Please recheck your inputs.\')]")).getText(), is("A necessary field \\\"\\\" was empty. Please recheck your inputs."));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addProjectTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageProjectsPage:AddProject");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Manage")).click();
    driver.findElement(By.linkText("Manage Projects")).click();
    driver.findElement(By.cssSelector(".form-title .button-small")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Project001");
    driver.findElement(By.name("status")).click();
    {
      WebElement dropdown = driver.findElement(By.name("status"));
      dropdown.findElement(By.xpath("//option[. = 'release']")).click();
    }
    driver.findElement(By.xpath("//option[@value=\'30\']")).click();
    driver.findElement(By.name("view_state")).click();
    driver.findElement(By.xpath("(//option[@value=\'10\'])[2]")).click();
    driver.findElement(By.name("description")).click();
    driver.findElement(By.name("description")).sendKeys("Description");
    driver.findElement(By.cssSelector(".button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Manage")));
    }
    driver.findElement(By.linkText("Manage")).click();
    driver.findElement(By.linkText("Manage Projects")).click();
    assertThat(driver.findElement(By.linkText("Project001")).getText(), is("Project001"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("release"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[4]")).getText(), is("public"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[5]")).getText(), is("Description"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addExistingProjectFailsTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageProjectsPage:AddExistingProjectFails");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Manage")).click();
    driver.findElement(By.linkText("Manage Projects")).click();
    driver.findElement(By.xpath("//input[@value=\'Create New Project\']")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Project001");
    driver.findElement(By.name("status")).click();
    {
      WebElement dropdown = driver.findElement(By.name("status"));
      dropdown.findElement(By.xpath("//option[. = 'release']")).click();
    }
    driver.findElement(By.xpath("//option[@value=\'30\']")).click();
    driver.findElement(By.name("view_state")).click();
    driver.findElement(By.xpath("(//option[@value=\'10\'])[2]")).click();
    driver.findElement(By.name("description")).click();
    driver.findElement(By.name("description")).sendKeys("Description");
    driver.findElement(By.xpath("//input[@value=\'Add Project\']")).click();
    assertThat(driver.findElement(By.xpath("//p[contains(.,\'A project with that name already exists. Please go back and enter a different name.\')]")).getText(), is("A project with that name already exists. Please go back and enter a different name."));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addCategoryTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageCategoryPage:AddCategory");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Manage")).click();
    driver.findElement(By.linkText("Manage Projects")).click();
    driver.findElement(By.linkText("Project001")).click();
    driver.findElement(By.xpath("(//input[@name=\'name\'])[2]")).click();
    driver.findElement(By.xpath("(//input[@name=\'name\'])[2]")).sendKeys("Category001");
    driver.findElement(By.xpath("//input[@value=\'Add Category\']")).click();
    assertThat(driver.findElement(By.xpath("//a/table/tbody/tr[3]/td")).getText(), is("Category001"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addExistingCategoryFailsTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageCategoryPage:AddExistingCategoryFails");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Manage")).click();
    driver.findElement(By.linkText("Manage Projects")).click();
    driver.findElement(By.linkText("Project001")).click();
    driver.findElement(By.xpath("(//input[@name=\'name\'])[2]")).click();
    driver.findElement(By.xpath("(//input[@name=\'name\'])[2]")).sendKeys("Category001");
    driver.findElement(By.xpath("//input[@value=\'Add Category\']")).click();
    assertThat(driver.findElement(By.xpath("//p[contains(.,\'A category with that name already exists.\')]")).getText(), is("A category with that name already exists."));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addIssueTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageIssuePage:AddIssue");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Report Issue")).click();
    driver.findElement(By.name("category_id")).click();
    {
      WebElement dropdown = driver.findElement(By.name("category_id"));
      dropdown.findElement(By.xpath("//option[. = 'Category001']")).click();
    }
    driver.findElement(By.name("reproducibility")).click();
    {
      WebElement dropdown = driver.findElement(By.name("reproducibility"));
      dropdown.findElement(By.xpath("//option[. = 'random']")).click();
    }
    driver.findElement(By.xpath("//option[@value=\'50\']")).click();
    driver.findElement(By.name("severity")).click();
    {
      WebElement dropdown = driver.findElement(By.name("severity"));
      dropdown.findElement(By.xpath("//option[. = 'crash']")).click();
    }
    driver.findElement(By.xpath("(//option[@value=\'70\'])[2]")).click();
    driver.findElement(By.name("priority")).click();
    {
      WebElement dropdown = driver.findElement(By.name("priority"));
      dropdown.findElement(By.xpath("//option[. = 'immediate']")).click();
    }
    driver.findElement(By.xpath("(//option[@value=\'60\'])[2]")).click();
    driver.findElement(By.name("summary")).click();
    driver.findElement(By.name("summary")).sendKeys("Summary001");
    driver.findElement(By.name("description")).click();
    driver.findElement(By.name("description")).sendKeys("description001");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("View Issues")).click();
    assertThat(driver.findElement(By.xpath("//table[@id=\'buglist\']/tbody/tr[4]/td[6]")).getText(), is("Category001"));
    assertThat(driver.findElement(By.xpath("//table[@id=\'buglist\']/tbody/tr[4]/td[7]/span")).getText(), is("crash"));
    assertThat(driver.findElement(By.xpath("//table[@id=\'buglist\']/tbody/tr[4]/td[10]")).getText(), is("Summary001"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void assignIssueTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageIssuePage:AssignIssue");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("View Issues")).click();
    driver.findElement(By.name("bug_arr[]")).click();
    driver.findElement(By.name("action")).click();
    {
      WebElement dropdown = driver.findElement(By.name("action"));
      dropdown.findElement(By.xpath("//option[. = 'Assign']")).click();
    }
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.cssSelector(".button")).click();
    assertThat(driver.findElement(By.linkText("administrator")).getText(), is("administrator"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void updateIssuePriorityTest() {
    driver.get("http://localhost:3000/mantisbt/login_page.php");
    System.out.println("{ASSESSOR}:ManageIssuePage:UpdateIssuePriority");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("administrator");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("View Issues")).click();
    driver.findElement(By.xpath("//img[@alt=\'Edit\']")).click();
    driver.findElement(By.name("priority")).click();
    {
      WebElement dropdown = driver.findElement(By.name("priority"));
      dropdown.findElement(By.xpath("//option[. = 'low']")).click();
    }
    driver.findElement(By.cssSelector(".button")).click();
    assertThat(driver.findElement(By.xpath("//tr[7]/td[2]")).getText(), is("low"));
    driver.findElement(By.linkText("Logout")).click();
  }
}
