package TestCases.PO.Claroline;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CoursePage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public CoursePage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_ID_login(String key1) {
        By elem = By.id("login");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void set_ID_password(String key2) {
        By elem = By.id("password");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key2);
    }

    public void click_CSSSELECTOR_buttonnth_child11() {
        By elem = By.cssSelector("button:nth-child(11)");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_001_Course001() {
        By elem = By.linkText("001 - Course001");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_CSSSELECTOR_CLCALclItemTool() {
        By elem = By.cssSelector("#CLCAL > .clItemTool");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Addanevent() {
        By elem = By.linkText("Add an event");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_ID_title(String key3) {
        By elem = By.id("title");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key3);
    }

    public void click_ID_fday() {
        By elem = By.id("fday");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_CSSSELECTOR_fdayoptionnth_child31() {
        By elem = By.cssSelector("#fday > option:nth-child(31)");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_fmonth() {
        By elem = By.id("fmonth");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_CSSSELECTOR_fmonthoptionnth_child5() {
        By elem = By.cssSelector("#fmonth > option:nth-child(5)");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_fyear(String key4) {
        By elem = By.id("fyear");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key4 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_CSSSELECTOR_fyearoptionnth_child2() {
        By elem = By.cssSelector("#fyear > option:nth-child(2)");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_ID_location(String key5) {
        By elem = By.id("location");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key5);
    }

    public void click_NAME_submitEvent() {
        By elem = By.name("submitEvent");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void AddCourseEvent(String key1, String key2, String key3, String key4, String key5) {
        set_ID_login(key1);
        set_ID_password(key2);
        click_CSSSELECTOR_buttonnth_child11();
        click_LINKTEXT_001_Course001();
        click_CSSSELECTOR_CLCALclItemTool();
        click_LINKTEXT_Addanevent();
        set_ID_title(key3);
        click_ID_fday();
        click_CSSSELECTOR_fdayoptionnth_child31();
        click_ID_fmonth();
        click_CSSSELECTOR_fmonthoptionnth_child5();
        click_ID_fyear(key4);
        click_CSSSELECTOR_fyearoptionnth_child2();
        set_ID_location(key5);
        click_NAME_submitEvent();
    }

    public List<WebElement> set_CSSSELECTOR_claroDialogMsg() {
        By elem = By.cssSelector(".claroDialogMsg");
        MyUtils.WaitForElementLoaded(driver, elem);
        List<WebElement> elements = driver.findElements(elem);
        return elements;
    }

    public void click_LINKTEXT_Logout() {
        By elem = By.linkText("Logout");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_CLQWZ() {
        By elem = By.id("CLQWZ");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Newexercise() {
        By elem = By.linkText("New exercise");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_CSSSELECTOR_divinput() {
        By elem = By.cssSelector("div > input");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void AddCourseExercise(String key1, String key2, String key3) {
        set_ID_login(key1);
        set_ID_password(key2);
        click_CSSSELECTOR_buttonnth_child11();
        click_LINKTEXT_001_Course001();
        click_ID_CLQWZ();
        click_LINKTEXT_Newexercise();
        set_ID_title(key3);
        click_CSSSELECTOR_divinput();
    }

    public void click_CSSSELECTOR_invisiblenth_child2tdnth_child4img() {
        By elem = By.cssSelector(".invisible:nth-child(2) > td:nth-child(4) img");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void MakeCourseExerciseVisible(String key1, String key2) {
        set_ID_login(key1);
        set_ID_password(key2);
        click_CSSSELECTOR_buttonnth_child11();
        click_LINKTEXT_001_Course001();
        click_ID_CLQWZ();
        click_CSSSELECTOR_invisiblenth_child2tdnth_child4img();
        click_LINKTEXT_Logout();
    }

    public void click_CSSSELECTOR_trnth_child2tdnth_child2img() {
        By elem = By.cssSelector("tr:nth-child(2) > td:nth-child(2) img");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Newquestion() {
        By elem = By.linkText("New question");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_MCUA() {
        By elem = By.id("MCUA");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_correct_1() {
        By elem = By.id("correct_1");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_NAME_grade_1(String key4) {
        By elem = By.name("grade_1");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key4);
    }

    public void set_NAME_grade_2(String key5) {
        By elem = By.name("grade_2");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key5);
    }

    public void click_NAME_cmdOk() {
        By elem = By.name("cmdOk");
        // Scroll into view
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", driver.findElement(elem));
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    // CUSTOM COMMAND
    public void click_NAME_cmdOk_to_XPATH() {
        By elem = By.xpath("/html/body/div[1]/div[2]/div[2]/div[3]/div[2]/form/div[2]/input");
        // Scroll into view
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", driver.findElement(elem));
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_NAME_LAST_QUESTION_CONFIRMATION() {
        By elem = By.name("cmdOk");
        // Scroll into view
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", driver.findElement(elem));
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }


    public void set_ID_title_1() {
        By elem = By.id("title");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputidtitle(String key6) {
        By elem = By.xpath("//input[@id=\'title\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key6);
    }

    public void click_XPATH_inputidTF() {
        By elem = By.xpath("//input[@id=\'TF\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_dividcourseRightContentformdiv2input() {
        By elem = By.xpath("//div[@id=\'courseRightContent\']/form/div[2]/input");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_inputidtrueCorrect() {
        By elem = By.xpath("//input[@id=\'trueCorrect\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputnametrueGrade(String key7) {
        By elem = By.xpath("//input[@name=\'trueGrade\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key7);
    }

    public void set_XPATH_inputnamefalseGrade(String key8) {
        By elem = By.xpath("//input[@name=\'falseGrade\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key8);
    }

    public void click_XPATH_inputnamecmdOk() {
        By elem = By.xpath("//input[@name=\'cmdOk\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_acontainstextNewquestion() {
        By elem = By.xpath("//a[contains(text(),\'New question\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputidtitle_1(String key9) {
        By elem = By.xpath("//input[@id=\'title\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key9);
    }

    public void click_XPATH_inputidMCMA() {
        By elem = By.xpath("//input[@id=\'MCMA\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_inputnamecmdAddAnsw() {
        By elem = By.xpath("//input[@name=\'cmdAddAnsw\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_inputidcorrect_1() {
        By elem = By.xpath("//input[@id=\'correct_1\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputnamegrade_1(String key10) {
        By elem = By.xpath("//input[@name=\'grade_1\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key10);
    }

    public void click_XPATH_inputnamegrade_2() {
        By elem = By.xpath("//input[@name=\'grade_2\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputnamegrade_3(String key11) {
        By elem = By.xpath("//input[@name=\'grade_3\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key11);
    }

    public void click_XPATH_acontainstextExercise001() {
        By elem = By.xpath("//a[contains(text(),\'Exercise 001\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_dividcourseRightContenttabletbodytrtd2() {
        By elem = By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr/td[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddCourseExerciseQuestions(String key1, String key2, String key3, String key4, String key5, String key6, String key7, String key8, String key9, String key10, String key11) {
        set_ID_login(key1);
        set_ID_password(key2);
        click_CSSSELECTOR_buttonnth_child11();
        click_LINKTEXT_001_Course001();
        click_ID_CLQWZ();
        click_CSSSELECTOR_trnth_child2tdnth_child2img();
        click_LINKTEXT_Newquestion();
        set_ID_title(key3);
        click_ID_MCUA();
        click_CSSSELECTOR_divinput();
        click_ID_correct_1();
        set_NAME_grade_1(key4);
        set_NAME_grade_2(key5);
        click_NAME_cmdOk();
        click_XPATH_acontainstextNewquestion();
        set_ID_title_1();
        set_XPATH_inputidtitle(key6);
        click_XPATH_inputidTF();
        click_XPATH_dividcourseRightContentformdiv2input();
        click_XPATH_inputidtrueCorrect();
        set_XPATH_inputnametrueGrade(key7);
        set_XPATH_inputnamefalseGrade(key8);
        click_XPATH_inputnamecmdOk();
        click_XPATH_acontainstextNewquestion();
        
        set_XPATH_inputidtitle_1(key9);
        click_XPATH_inputidMCMA();
        click_NAME_cmdOk_to_XPATH();
        click_XPATH_inputnamecmdAddAnsw();
        click_XPATH_inputidcorrect_1();
        set_XPATH_inputnamegrade_1(key10);
        click_XPATH_inputnamegrade_2();
        set_XPATH_inputnamegrade_3(key11);
        click_NAME_LAST_QUESTION_CONFIRMATION();

        click_XPATH_acontainstextExercise001();
        set_XPATH_dividcourseRightContenttabletbodytrtd2();
    }

    public String set_XPATH_dividcourseRightContenttabletbodytrtd2_1() {
        By elem = By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr/td[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_dividcourseRightContenttabletbodytrtd4small() {
        By elem = By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr/td[4]/small");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_dividcourseRightContenttabletbodytr2td2() {
        By elem = By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr[2]/td[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_dividcourseRightContenttabletbodytr2td4() {
        By elem = By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr[2]/td[4]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_dividcourseRightContenttabletbodytr3td2() {
        By elem = By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr[3]/td[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_dividcourseRightContenttabletbodytr3td4small() {
        By elem = By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr[3]/td[4]/small");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }
}
