package TestCases.PO.Claroline;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class PlatformAdministratorPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public PlatformAdministratorPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_ID_login(String key1) {
        By elem = By.id("login");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void set_ID_password(String key2) {
        By elem = By.id("password");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key2);
    }

    public void click_CSSSELECTOR_buttonnth_child11() {
        By elem = By.cssSelector("button:nth-child(11)");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Platformadministration() {
        By elem = By.linkText("Platform administration");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Createuser() {
        By elem = By.linkText("Create user");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_ID_lastname(String key3) {
        By elem = By.id("lastname");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key3);
    }

    public void set_ID_firstname(String key4) {
        By elem = By.id("firstname");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key4);
    }

    public void set_ID_username(String key5) {
        By elem = By.id("username");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key5);
    }

    public void set_XPATH_inputidpassword(String key6) {
        By elem = By.xpath("//input[@id=\'password\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key6);
    }

    public void set_XPATH_inputidpassword_conf(String key7) {
        By elem = By.xpath("//input[@id=\'password_conf\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key7);
    }

    public void click_XPATH_inputidstudent() {
        By elem = By.xpath("//input[@id=\'student\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_applyChange() {
        By elem = By.id("applyChange");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_div2div2div() {
        By elem = By.xpath("//div[2]/div[2]/div");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddUser(String key1, String key2, String key3, String key4, String key5, String key6, String key7) {
        set_ID_login(key1);
        set_ID_password(key2);
        click_CSSSELECTOR_buttonnth_child11();
        click_LINKTEXT_Platformadministration();
        click_LINKTEXT_Createuser();
        set_ID_lastname(key3);
        set_ID_firstname(key4);
        set_ID_username(key5);
        set_XPATH_inputidpassword(key6);
        set_XPATH_inputidpassword_conf(key7);
        click_XPATH_inputidstudent();
        click_ID_applyChange();
        set_XPATH_div2div2div();
    }

    public String set_XPATH_div2div2div_1() {
        By elem = By.xpath("//div[2]/div[2]/div");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void click_LINKTEXT_Logout() {
        By elem = By.linkText("Logout");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_ID_search_user(String key3) {
        By elem = By.id("search_user");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key3);
    }

    public void click_CSSSELECTOR_adminUserinputnth_child2() {
        By elem = By.cssSelector(".adminUser input:nth-child(2)");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_ID_L0() {
        By elem = By.id("L0");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void SearchUser(String key1, String key2, String key3) {
        set_ID_login(key1);
        set_ID_password(key2);
        click_CSSSELECTOR_buttonnth_child11();
        click_LINKTEXT_Platformadministration();
        set_ID_search_user(key3);
        click_CSSSELECTOR_adminUserinputnth_child2();
        set_ID_L0();
    }

    public String set_ID_L0_1() {
        By elem = By.id("L0");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_CSSSELECTOR_tdnth_child3() {
        By elem = By.cssSelector("td:nth-child(3)");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_CSSSELECTOR_tdnth_child6() {
        By elem = By.cssSelector("td:nth-child(6)");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void click_LINKTEXT_Createcourse() {
        By elem = By.linkText("Create course");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_ID_course_title(String key3) {
        By elem = By.id("course_title");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key3);
    }

    public void set_ID_course_officialCode() {
        By elem = By.id("course_officialCode");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_ID_course_officialCode_1(String key4, String key5) {
        By elem = By.id("course_officialCode");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key4);
        {
            elem = By.id("mslist2");
            MyUtils.WaitForElementLoaded(driver, elem);
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key5 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_CSSSELECTOR_msremoveimg(String key6) {
        By elem = By.cssSelector(".msremove > img");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            elem = By.id("mslist2");
            MyUtils.WaitForElementLoaded(driver, elem);
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key6 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_CSSSELECTOR_msremoveimg_1() {
        By elem = By.cssSelector(".msremove > img");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_access_public() {
        By elem = By.id("access_public");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_registration_true() {
        By elem = By.id("registration_true");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_NAME_changeProperties() {
        By elem = By.name("changeProperties");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void AddCourse(String key1, String key2, String key3, String key4, String key5, String key6) {
        set_ID_login(key1);
        set_ID_password(key2);
        click_CSSSELECTOR_buttonnth_child11();
        click_LINKTEXT_Platformadministration();
        click_LINKTEXT_Createcourse();
        set_ID_course_title(key3);
        set_ID_course_officialCode();
        set_ID_course_officialCode_1(key4, key5);
        click_CSSSELECTOR_msremoveimg(key6);
        click_CSSSELECTOR_msremoveimg_1();
        click_ID_access_public();
        click_ID_registration_true();
        click_NAME_changeProperties();
    }

    public List<WebElement> set_CSSSELECTOR_claroDialogMsg() {
        By elem = By.cssSelector(".claroDialogMsg");
        MyUtils.WaitForElementLoaded(driver, elem);
        List<WebElement> elements = driver.findElements(elem);
        return elements;
    }

    public void click_LINKTEXT_Continue() {
        By elem = By.linkText("Continue");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        click_LINKTEXT_Logout();
    }

    public void set_ID_search_course(String key3) {
        By elem = By.id("search_course");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key3);
    }

    public void click_CSSSELECTOR_adminCourseinputnth_child2() {
        By elem = By.cssSelector(".adminCourse input:nth-child(2)");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_CSSSELECTOR_tbodynth_child2tdnth_child2() {
        By elem = By.cssSelector("tbody:nth-child(2) td:nth-child(2)");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void SearchCourse(String key1, String key2, String key3) {
        set_ID_login(key1);
        set_ID_password(key2);
        click_CSSSELECTOR_buttonnth_child11();
        click_LINKTEXT_Platformadministration();
        set_ID_search_course(key3);
        click_CSSSELECTOR_adminCourseinputnth_child2();
        set_CSSSELECTOR_tbodynth_child2tdnth_child2();
    }

    public String set_CSSSELECTOR_tbodynth_child2tdnth_child2_1() {
        By elem = By.cssSelector("tbody:nth-child(2) td:nth-child(2)");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }
}
