package TestCases.PO.MantisBT;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ManageIssuePage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public ManageIssuePage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_NAME_username(String key1) {
        By elem = By.name("username");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void set_NAME_password(String key2) {
        By elem = By.name("password");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key2);
    }

    public void click_CSSSELECTOR_button() {
        By elem = By.cssSelector(".button");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_ReportIssue() {
        By elem = By.linkText("Report Issue");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_NAME_category_id(String key3) {
        By elem = By.name("category_id");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key3 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_NAME_reproducibility(String key4) {
        By elem = By.name("reproducibility");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key4 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_XPATH_optionvalue50(String key5) {
        By elem = By.xpath("//option[@value=\'50\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_NAME_severity(String key6) {
        By elem = By.name("severity");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key6 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_XPATH_optionvalue702(String key7) {
        By elem = By.xpath("(//option[@value=\'70\'])[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_NAME_priority(String key8) {
        By elem = By.name("priority");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key8 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_XPATH_optionvalue602(String key9) {
        By elem = By.xpath("(//option[@value=\'60\'])[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_NAME_summary(String key10) {
        By elem = By.name("summary");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key10);
    }

    public void set_NAME_description(String key11) {
        By elem = By.name("description");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key11);
    }

    public void click_BUTTON_confirmIssue() {
        By elem = By.xpath("/html/body/div[2]/form/table/tbody/tr[16]/td[2]/input");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_ViewIssues() {
        By elem = By.linkText("View Issues");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_tableidbuglisttbodytr4td6() {
        By elem = By.xpath("//table[@id=\'buglist\']/tbody/tr[4]/td[6]");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddIssue(String key1, String key2, String key3, String key4, String key5, String key6, String key7, String key8, String key9, String key10, String key11) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_ReportIssue();
        click_NAME_category_id(key3);
        click_NAME_reproducibility(key4);
        click_XPATH_optionvalue50(key5);
        click_NAME_severity(key6);
        click_XPATH_optionvalue702(key7);
        click_NAME_priority(key8);
        click_XPATH_optionvalue602(key9);
        set_NAME_summary(key10);
        set_NAME_description(key11);
        click_BUTTON_confirmIssue();
        click_LINKTEXT_ViewIssues();
        set_XPATH_tableidbuglisttbodytr4td6();
    }

    public String set_XPATH_tableidbuglisttbodytr4td6_1() {
        By elem = By.xpath("//table[@id=\'buglist\']/tbody/tr[4]/td[6]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_tableidbuglisttbodytr4td7span() {
        By elem = By.xpath("//table[@id=\'buglist\']/tbody/tr[4]/td[7]/span");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_tableidbuglisttbodytr4td10() {
        By elem = By.xpath("//table[@id=\'buglist\']/tbody/tr[4]/td[10]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void click_LINKTEXT_Logout() {
        By elem = By.linkText("Logout");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_NAME_bug_arr() {
        By elem = By.name("bug_arr[]");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_NAME_action(String key3) {
        By elem = By.name("action");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key3 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void set_LINKTEXT_administrator() {
        By elem = By.linkText("administrator");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void click_BUTTON_assignIssue() {
        By elem = By.xpath("/html/body/form/table/tbody/tr[5]/td/span[1]/input[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();

        By elem2 = By.xpath("/html/body/div[2]/form/table/tbody/tr[2]/td/input");
        MyUtils.WaitForElementLoaded(driver, elem2);
        driver.findElement(elem2).click();
        
    }

    public void AssignIssue(String key1, String key2, String key3) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_ViewIssues();
        click_NAME_bug_arr();
        click_NAME_action(key3);
        click_BUTTON_assignIssue();
        set_LINKTEXT_administrator();
    }

    public String set_LINKTEXT_administrator_1() {
        By elem = By.linkText("administrator");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void click_XPATH_imgaltEdit() {
        By elem = By.xpath("//img[@alt=\'Edit\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_tr7td2() {
        By elem = By.xpath("//tr[7]/td[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void UpdateIssuePriority(String key1, String key2, String key3) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_ViewIssues();
        click_XPATH_imgaltEdit();
        click_NAME_priority(key3);
        click_CSSSELECTOR_button();
        set_XPATH_tr7td2();
    }

    public String set_XPATH_tr7td2_1() {
        By elem = By.xpath("//tr[7]/td[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }
}
