package TestCases.PO.MantisBT;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class ManageProjectsPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public ManageProjectsPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_NAME_username(String key1) {
        By elem = By.name("username");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void set_NAME_password(String key2) {
        By elem = By.name("password");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key2);
    }

    public void click_CSSSELECTOR_button() {
        By elem = By.cssSelector(".button");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Manage() {
        By elem = By.linkText("Manage");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_ManageProjects() {
        By elem = By.linkText("Manage Projects");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_CSSSELECTOR_form_titlebutton_small() {
        By elem = By.cssSelector(".form-title .button-small");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_NAME_name(String key3) {
        By elem = By.name("name");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key3);
    }

    public void click_NAME_status(String key4) {
        By elem = By.name("status");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key4 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_XPATH_optionvalue30(String key5) {
        By elem = By.xpath("//option[@value=\'30\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_NAME_view_state() {
        By elem = By.name("view_state");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_optionvalue102(String key6) {
        By elem = By.xpath("(//option[@value=\'10\'])[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_NAME_description(String key7) {
        By elem = By.name("description");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key7);
    }

    public void click_CSSSELECTOR_button_1() {
        By elem = By.cssSelector(".button");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
            elem = By.linkText("Manage");
            MyUtils.WaitForElementLoaded(driver, elem);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Manage")));
        }
    }

    public void set_LINKTEXT_Project001() {
        By elem = By.linkText("Project001");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddProject(String key1, String key2, String key3, String key4, String key5, String key6, String key7) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_Manage();
        click_LINKTEXT_ManageProjects();
        click_CSSSELECTOR_form_titlebutton_small();
        set_NAME_name(key3);
        click_NAME_status(key4);
        click_XPATH_optionvalue30(key5);
        click_NAME_view_state();
        click_XPATH_optionvalue102(key6);
        set_NAME_description(key7);
        click_CSSSELECTOR_button_1();
        set_LINKTEXT_Project001();
    }

    public String set_LINKTEXT_Project001_1() {
        By elem = By.linkText("Project001");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_tr3td2() {
        By elem = By.xpath("//tr[3]/td[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_tr3td4() {
        By elem = By.xpath("//tr[3]/td[4]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public String set_XPATH_tr3td5() {
        By elem = By.xpath("//tr[3]/td[5]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void click_LINKTEXT_Logout() {
        By elem = By.linkText("Logout");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_inputvalueCreateNewProject(String key3) {
        By elem = By.xpath("//input[@value=\'Create New Project\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_inputvalueAddProject(String key9) {
        By elem = By.xpath("//input[@value=\'Add Project\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_pcontainsAprojectwiththatnamealreadyexistsPleasegobackandenteradifferentname() {
        By elem = By.xpath("//p[contains(.,\'A project with that name already exists. Please go back and enter a different name.\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddExistingProjectFails(String key1, String key2, String key3, String key4, String key5, String key6, String key7, String key8, String key9) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_Manage();
        click_LINKTEXT_ManageProjects();
        click_XPATH_inputvalueCreateNewProject(key3);
        set_NAME_name(key4);
        click_NAME_status(key5);
        click_XPATH_optionvalue30(key6);
        click_NAME_view_state();
        click_XPATH_optionvalue102(key7);
        set_NAME_description(key8);
        click_XPATH_inputvalueAddProject(key9);
        set_XPATH_pcontainsAprojectwiththatnamealreadyexistsPleasegobackandenteradifferentname();
    }

    public String set_XPATH_pcontainsAprojectwiththatnamealreadyexistsPleasegobackandenteradifferentname_1() {
        By elem = By.xpath("//p[contains(.,\'A project with that name already exists. Please go back and enter a different name.\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }
}
