// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ClarolineTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addUserTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:PlatformAdministratorPage:AddUser");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("Platform administration")).click();
    driver.findElement(By.linkText("Create user")).click();
    driver.findElement(By.id("lastname")).click();
    driver.findElement(By.id("lastname")).sendKeys("Name001");
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("firstname001");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("user001");
    driver.findElement(By.xpath("//input[@id=\'password\']")).click();
    driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("password001");
    driver.findElement(By.xpath("//input[@id=\'password_conf\']")).click();
    driver.findElement(By.xpath("//input[@id=\'password_conf\']")).sendKeys("password001");
    driver.findElement(By.xpath("//input[@id=\'student\']")).click();
    driver.findElement(By.id("applyChange")).click();
    assertThat(driver.findElement(By.xpath("//div[2]/div[2]/div")).getText(), is("The new user has been sucessfully created"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void searchUserTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:PlatformAdministratorPage:SearchUser");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("Platform administration")).click();
    driver.findElement(By.id("search_user")).click();
    driver.findElement(By.id("search_user")).sendKeys("user001");
    driver.findElement(By.cssSelector(".adminUser input:nth-child(2)")).click();
    assertThat(driver.findElement(By.id("L0")).getText(), is("Name001"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(3)")).getText(), is("firstname001"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(6)")).getText(), is("User"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void loginUserTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:Login:LoginUser");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("user001");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password001");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    assertThat(driver.findElement(By.cssSelector(".blockHeader > .userName")).getText(), is("firstname001 Name001"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addCourseTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:PlatformAdministratorPage:AddCourse");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("Platform administration")).click();
    driver.findElement(By.linkText("Create course")).click();
    driver.findElement(By.id("course_title")).click();
    driver.findElement(By.id("course_title")).sendKeys("Course001");
    driver.findElement(By.id("course_officialCode")).click();
    driver.findElement(By.id("course_officialCode")).sendKeys("001");
    {
      WebElement dropdown = driver.findElement(By.id("mslist2"));
      dropdown.findElement(By.xpath("//option[. = 'Sciences']")).click();
    }
    driver.findElement(By.cssSelector(".msremove > img")).click();
    {
      WebElement dropdown = driver.findElement(By.id("mslist2"));
      dropdown.findElement(By.xpath("//option[. = 'Economics']")).click();
    }
    driver.findElement(By.cssSelector(".msremove > img")).click();
    driver.findElement(By.id("access_public")).click();
    driver.findElement(By.id("registration_true")).click();
    driver.findElement(By.name("changeProperties")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".claroDialogMsg"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void searchCourseTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:PlatformAdministratorPage:SearchCourse");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("Platform administration")).click();
    driver.findElement(By.id("search_course")).click();
    driver.findElement(By.id("search_course")).sendKeys("Course001");
    driver.findElement(By.cssSelector(".adminCourse input:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(2)")).getText(), is("Course001"));
    assertThat(driver.findElement(By.id("L0")).getText(), is("001"));
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void enrolUserTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:Enrol:EnrolUser");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("user001");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password001");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("Enrol on a new course")).click();
    driver.findElement(By.id("coursesearchbox_keyword")).click();
    driver.findElement(By.id("coursesearchbox_keyword")).sendKeys("Course001");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".enrolment")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".claroDialogMsg"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addCourseEventTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:CoursePage:AddCourseEvent");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("001 - Course001")).click();
    driver.findElement(By.cssSelector("#CLCAL > .clItemTool")).click();
    driver.findElement(By.linkText("Add an event")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("Exam 001");
    driver.findElement(By.id("fday")).click();
    driver.findElement(By.cssSelector("#fday > option:nth-child(31)")).click();
    driver.findElement(By.id("fmonth")).click();
    driver.findElement(By.cssSelector("#fmonth > option:nth-child(5)")).click();
    driver.findElement(By.id("fyear")).click();
    {
      WebElement dropdown = driver.findElement(By.id("fyear"));
      dropdown.findElement(By.xpath("//option[. = '2023']")).click();
    }
    driver.findElement(By.cssSelector("#fyear > option:nth-child(2)")).click();
    driver.findElement(By.id("location")).click();
    driver.findElement(By.id("location")).sendKeys("Genoa");
    driver.findElement(By.name("submitEvent")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".claroDialogMsg"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addCourseExerciseTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:CoursePage:AddCourseExercise");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("001 - Course001")).click();
    driver.findElement(By.id("CLQWZ")).click();
    driver.findElement(By.linkText("New exercise")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("Exercise 001");
    driver.findElement(By.cssSelector("div > input")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".claroDialogMsg"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void makeCourseExerciseVisibleTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:CoursePage:MakeCourseExerciseVisible");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("001 - Course001")).click();
    driver.findElement(By.id("CLQWZ")).click();
    driver.findElement(By.cssSelector(".invisible:nth-child(2) > td:nth-child(4) img")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
  @Test
  public void addCourseExerciseQuestionsTest() {
    driver.get("http://localhost:3000/claroline11110/index.php");
    System.out.println("{ASSESSOR}:CoursePage:AddCourseExerciseQuestions");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(11)")).click();
    driver.findElement(By.linkText("001 - Course001")).click();
    driver.findElement(By.id("CLQWZ")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) img")).click();
    driver.findElement(By.linkText("New question")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("Question 1");
    driver.findElement(By.id("MCUA")).click();
    driver.findElement(By.cssSelector("div > input")).click();
    driver.findElement(By.id("correct_1")).click();
    driver.findElement(By.name("grade_1")).click();
    driver.findElement(By.name("grade_1")).sendKeys("3");
    driver.findElement(By.name("grade_2")).click();
    driver.findElement(By.name("grade_2")).sendKeys("-3");
    driver.findElement(By.name("cmdOk")).click();
    driver.findElement(By.linkText("New question")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.xpath("//input[@id=\'title\']")).sendKeys("Question 2");
    driver.findElement(By.xpath("//input[@id=\'TF\']")).click();
    driver.findElement(By.xpath("//div[@id=\'courseRightContent\']/form/div[2]/input")).click();
    driver.findElement(By.xpath("//input[@id=\'trueCorrect\']")).click();
    driver.findElement(By.xpath("//input[@name=\'trueGrade\']")).click();
    driver.findElement(By.xpath("//input[@name=\'trueGrade\']")).sendKeys("3");
    driver.findElement(By.xpath("//input[@name=\'falseGrade\']")).click();
    driver.findElement(By.xpath("//input[@name=\'falseGrade\']")).sendKeys("-3");
    driver.findElement(By.xpath("//input[@name=\'cmdOk\']")).click();
    driver.findElement(By.xpath("//a[contains(text(),\'New question\')]")).click();
    driver.findElement(By.xpath("//input[@id=\'title\']")).click();
    driver.findElement(By.xpath("//input[@id=\'title\']")).sendKeys("Question 3");
    driver.findElement(By.xpath("//input[@id=\'MCMA\']")).click();
    driver.findElement(By.xpath("//div[@id=\'courseRightContent\']/form/div[2]/input")).click();
    driver.findElement(By.xpath("//input[@name=\'cmdAddAnsw\']")).click();
    driver.findElement(By.xpath("//input[@id=\'correct_1\']")).click();
    driver.findElement(By.xpath("//input[@name=\'grade_1\']")).click();
    driver.findElement(By.xpath("//input[@name=\'grade_1\']")).sendKeys("3");
    driver.findElement(By.xpath("//input[@name=\'grade_2\']")).click();
    driver.findElement(By.xpath("//input[@name=\'grade_3\']")).click();
    driver.findElement(By.xpath("//input[@name=\'grade_3\']")).sendKeys("-3");
    driver.findElement(By.xpath("//input[@name=\'cmdOk\']")).click();
    driver.findElement(By.xpath("//a[contains(text(),\'Exercise 001\')]")).click();
    assertThat(driver.findElement(By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr/td[2]")).getText(), is("Question 1"));
    assertThat(driver.findElement(By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr/td[4]/small")).getText(), is("Multiple choice (Unique answer)"));
    assertThat(driver.findElement(By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr[2]/td[2]")).getText(), is("Question 2"));
    assertThat(driver.findElement(By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr[2]/td[4]")).getText(), is("True/False"));
    assertThat(driver.findElement(By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr[3]/td[2]")).getText(), is("Question 3"));
    assertThat(driver.findElement(By.xpath("//div[@id=\'courseRightContent\']/table/tbody/tr[3]/td[4]/small")).getText(), is("Multiple choice (Multiple answers)"));
    driver.findElement(By.linkText("Logout")).click();
  }
}
