package TestCases.PO.MantisBT;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ManageCategoryPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public ManageCategoryPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_NAME_username(String key1) {
        By elem = By.name("username");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void set_NAME_password(String key2) {
        By elem = By.name("password");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key2);
    }

    public void click_CSSSELECTOR_button() {
        By elem = By.cssSelector(".button");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Manage() {
        By elem = By.linkText("Manage");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_ManageProjects() {
        By elem = By.linkText("Manage Projects");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Project001() {
        By elem = By.linkText("Project001");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputnamename2(String key3) {
        By elem = By.xpath("(//input[@name=\'name\'])[2]");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key3);
    }

    public void click_XPATH_inputvalueAddCategory(String key4) {
        By elem = By.xpath("//input[@value=\'Add Category\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_atabletbodytr3td() {
        By elem = By.xpath("//a/table/tbody/tr[3]/td");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddCategory(String key1, String key2, String key3, String key4) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_Manage();
        click_LINKTEXT_ManageProjects();
        click_LINKTEXT_Project001();
        set_XPATH_inputnamename2(key3);
        click_XPATH_inputvalueAddCategory(key4);
        set_XPATH_atabletbodytr3td();
    }

    public String set_XPATH_atabletbodytr3td_1() {
        By elem = By.xpath("//a/table/tbody/tr[3]/td");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void click_LINKTEXT_Logout() {
        By elem = By.linkText("Logout");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_pcontainsAcategorywiththatnamealreadyexists() {
        By elem = By.xpath("//p[contains(.,\'A category with that name already exists.\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddExistingCategoryFails(String key1, String key2, String key3, String key4) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_Manage();
        click_LINKTEXT_ManageProjects();
        click_LINKTEXT_Project001();
        set_XPATH_inputnamename2(key3);
        click_XPATH_inputvalueAddCategory(key4);
        set_XPATH_pcontainsAcategorywiththatnamealreadyexists();
    }

    public String set_XPATH_pcontainsAcategorywiththatnamealreadyexists_1() {
        By elem = By.xpath("//p[contains(.,\'A category with that name already exists.\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }
}
