package TestCases.PO.MantisBT;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ManageUserPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public ManageUserPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_NAME_username(String key1) {
        By elem = By.name("username");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void set_NAME_password(String key2) {
        By elem = By.name("password");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key2);
    }

    public void click_CSSSELECTOR_button() {
        By elem = By.cssSelector(".button");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Manage() {
        By elem = By.linkText("Manage");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_ManageUsers() {
        By elem = By.linkText("Manage Users");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_CSSSELECTOR_form_titlebutton_small() {
        By elem = By.cssSelector(".form-title .button-small");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_NAME_username_1() {
        By elem = By.name("username");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputnameusername(String key3) {
        By elem = By.xpath("//input[@name=\'username\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key3);
    }

    public void click_NAME_realname() {
        By elem = By.name("realname");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputnamerealname(String key4) {
        By elem = By.xpath("//input[@name=\'realname\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key4);
    }

    public void click_NAME_email() {
        By elem = By.name("email");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_inputnameemail(String key5) {
        By elem = By.xpath("//input[@name=\'email\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key5);
    }

    public void click_NAME_access_level(String key6) {
        By elem = By.name("access_level");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.xpath("//option[. = '" + key6 + "']");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void click_XPATH_optionvalue40(String key7) {
        By elem = By.xpath("//option[@value=\'40\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void AddUser(String key1, String key2, String key3, String key4, String key5, String key6, String key7) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_Manage();
        click_LINKTEXT_ManageUsers();
        click_CSSSELECTOR_form_titlebutton_small();
        set_NAME_username_1();
        set_XPATH_inputnameusername(key3);
        click_NAME_realname();
        set_XPATH_inputnamerealname(key4);
        click_NAME_email();
        set_XPATH_inputnameemail(key5);
        click_NAME_access_level(key6);
        click_XPATH_optionvalue40(key7);
    }

    public String set_NAME_username_2() {
        By elem = By.name("username");
        MyUtils.WaitForElementLoaded(driver, elem);
        String value = driver.findElement(elem).getAttribute("value");
        return value;
    }

    public void click_LINKTEXT_Logout() {
        By elem = By.linkText("Logout");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_inputvalueCreateNewAccount(String key3) {
        By elem = By.xpath("//input[@value=\'Create New Account\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_XPATH_inputvalueCreateUser(String key9) {
        By elem = By.xpath("//input[@value=\'Create User\']");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void set_XPATH_pcontainsThatusernameisalreadybeingusedPleasegobackandselectanotherone() {
        By elem = By.xpath("//p[contains(.,\'That username is already being used. Please go back and select another one.\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddExistingUserFails(String key1, String key2, String key3, String key4, String key5, String key6, String key7, String key8, String key9) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_Manage();
        click_LINKTEXT_ManageUsers();
        click_XPATH_inputvalueCreateNewAccount(key3);
        set_NAME_username_1();
        set_XPATH_inputnameusername(key4);
        click_NAME_realname();
        set_XPATH_inputnamerealname(key5);
        click_NAME_email();
        set_XPATH_inputnameemail(key6);
        click_NAME_access_level(key7);
        click_XPATH_optionvalue40(key8);
        click_XPATH_inputvalueCreateUser(key9);
        set_XPATH_pcontainsThatusernameisalreadybeingusedPleasegobackandselectanotherone();
    }

    public String set_XPATH_pcontainsThatusernameisalreadybeingusedPleasegobackandselectanotherone_1() {
        By elem = By.xpath("//p[contains(.,\'That username is already being used. Please go back and select another one.\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void set_XPATH_pcontainsAnecessaryfieldwasemptyPleaserecheckyourinputs() {
        By elem = By.xpath("//p[contains(.,\'A necessary field \"\" was empty. Please recheck your inputs.\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void AddEmptyUserFails(String key1, String key2, String key3, String key4) {
        set_NAME_username(key1);
        set_NAME_password(key2);
        click_CSSSELECTOR_button();
        click_LINKTEXT_Manage();
        click_LINKTEXT_ManageUsers();
        click_XPATH_inputvalueCreateNewAccount(key3);
        click_XPATH_inputvalueCreateUser(key4);
        set_XPATH_pcontainsAnecessaryfieldwasemptyPleaserecheckyourinputs();
    }

    public String set_XPATH_pcontainsAnecessaryfieldwasemptyPleaserecheckyourinputs_1() {
        By elem = By.xpath("//p[contains(.,\'A necessary field \"\" was empty. Please recheck your inputs.\')]");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }
}
